services:
  app:
    image: analytics-api:v1
    ports: 
      - "8002:8002"
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - PORT=8002  
    #   - DATABASE_URL=postgresql://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env.compose
    depends_on:
      db_service:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml

  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Nuttasak1605!
    - POSTGRES_DB=timescaledb
    ports:
    - "5432:5432"
    #expose:
    #- 5432
    volumes:
    - timescaledb_data:/var/lib/postgresql/data
    env_file:
    - .env.compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  timescaledb_data: